------------------------------
--CLEANING BASE IF NECESSARY--
------------------------------

DECLARE
   does_not_exist   EXCEPTION;
   PRAGMA EXCEPTION_INIT (does_not_exist, -942);
BEGIN

   EXECUTE IMMEDIATE 'DROP TABLE USERS';

EXCEPTION
   WHEN does_not_exist
   THEN
      NULL;
END;
/

DECLARE
   does_not_exist   EXCEPTION;
   PRAGMA EXCEPTION_INIT (does_not_exist, -942);
BEGIN

   EXECUTE IMMEDIATE 'DROP TABLE FUNCTIONALITIES ';

EXCEPTION
   WHEN does_not_exist
   THEN
      NULL;
END;
/


DECLARE
   does_not_exist   EXCEPTION;
   PRAGMA EXCEPTION_INIT (does_not_exist, -942);
BEGIN

   EXECUTE IMMEDIATE 'DROP TABLE PLUGINS';

EXCEPTION
   WHEN does_not_exist
   THEN
      NULL;
END;
/

DECLARE
   does_not_exist   EXCEPTION;
   PRAGMA EXCEPTION_INIT (does_not_exist, -942);
BEGIN

   EXECUTE IMMEDIATE 'DROP TABLE USERS_FUNC_PERMISSIONS ';

EXCEPTION
   WHEN does_not_exist
   THEN
      NULL;
END;
/


------------------------------
--CLEANING SEQUENCES IF NECESSARY--
------------------------------


DECLARE
   does_not_exist   EXCEPTION;
   PRAGMA EXCEPTION_INIT (does_not_exist, -02289);
BEGIN

   EXECUTE IMMEDIATE 'DROP SEQUENCE USERS_SEQ';

EXCEPTION
   WHEN does_not_exist
   THEN
      NULL;
END;
/

DECLARE
   does_not_exist   EXCEPTION;
   PRAGMA EXCEPTION_INIT (does_not_exist, -02289);
BEGIN

   EXECUTE IMMEDIATE 'DROP SEQUENCE FUNCTIONALITIES_SEQ ';

EXCEPTION
   WHEN does_not_exist
   THEN
      NULL;
END;
/


DECLARE
   does_not_exist   EXCEPTION;
   PRAGMA EXCEPTION_INIT (does_not_exist, -02289);
BEGIN

   EXECUTE IMMEDIATE 'DROP SEQUENCE PLUGINS_SEQ';

EXCEPTION
   WHEN does_not_exist
   THEN
      NULL;
END;
/


-------------------
--CREATING TABLES--
-------------------



CREATE TABLE USERS
(
  ID NUMBER(20) NOT NULL
, LOGIN VARCHAR2(50) NOT NULL
, FULL_NAME VARCHAR2(150)
, STATUS VARCHAR2(20)
, CURRENT_MANAGEMENT VARCHAR2(1)
, CONSTRAINT USERS_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);
CREATE SEQUENCE USERS_SEQ START WITH 1;
CREATE OR REPLACE TRIGGER USERS_TR
BEFORE INSERT ON USERS
FOR EACH ROW

BEGIN
  SELECT USERS_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   dual;
END;
/



CREATE TABLE PLUGINS
(
  ID NUMBER(20) NOT NULL
, NAME VARCHAR2(50) NOT NULL UNIQUE
, DESCRIPTION VARCHAR2(500)
, START_DATE DATE DEFAULT SYSDATE NOT NULL
, CONSTRAINT PLUGINS_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);
CREATE SEQUENCE PLUGINS_SEQ START WITH 1;
CREATE OR REPLACE TRIGGER PLUGINS_TR
BEFORE INSERT ON PLUGINS
FOR EACH ROW

BEGIN
  SELECT PLUGINS_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   dual;
END;
/


CREATE TABLE FUNCTIONALITIES
(
  ID NUMBER(20) NOT NULL
, NAME VARCHAR2(50) NOT NULL UNIQUE
, DESCRIPTION VARCHAR2(500)
, START_DATE DATE DEFAULT SYSDATE NOT NULL
, PLUGIN_ID NUMBER(20) NOT NULL
, CONSTRAINT FUNCTIONALITIES_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
, CONSTRAINT FK_FUNCTIONALITIES_PLUGIN_ID FOREIGN KEY
  (
    PLUGIN_ID
  )
  REFERENCES PLUGINS

);
CREATE SEQUENCE FUNCTIONALITIES_SEQ START WITH 1;
CREATE OR REPLACE TRIGGER FUNCTIONALITIES_TR
BEFORE INSERT ON FUNCTIONALITIES
FOR EACH ROW

BEGIN
  SELECT FUNCTIONALITIES_SEQ.NEXTVAL
  INTO   :NEW.ID
  FROM   dual;
END;
/




CREATE TABLE USERS_FUNC_PERMISSIONS
(
  USER_ID NUMBER(20) NOT NULL
, FUNCTIONALITY_ID NUMBER(20) NOT NULL
, CONSTRAINT USERS_FUNC_PERMISSIONS_PK PRIMARY KEY
  (
    USER_ID, FUNCTIONALITY_ID
  )
  ENABLE
);

-------------
--ADD USERS--
-------------

INSERT INTO USERS (ID, LOGIN, FULL_NAME, STATUS, CURRENT_MANAGEMENT) VALUES (1, 'ADMIN', 'JOSE ADMIN', 'ACTIVE', 'Y');
INSERT INTO USERS (ID, LOGIN, FULL_NAME, STATUS, CURRENT_MANAGEMENT) VALUES (2, 'ALMOST_ADMIN', 'ADMIN JR', 'ACTIVE', 'Y');